# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, haskeline, mtl }:

cabal.mkDerivation (self: {
  pname = "repline";
  version = "0.1.0.0";
  sha256 = "0da55c00f95261998b5618515ef3663bae0ca3aefb882e312c666d7ac409f6a9";
  buildDepends = [ haskeline mtl ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
