# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, haskeline, mtl }:

cabal.mkDerivation (self: {
  pname = "repline";
  version = "0.1.0.0";
  sha256 = "5e40fabee2825e5c18c1fdab338960d568d9a0dd7175cc6b13120f65a67567e2";
  buildDepends = [ haskeline mtl ];
  meta = {
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
